# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: model.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bmodel.proto\x12\x05proto\"(\n\x07Request\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07payload\x18\x02 \x01(\x0c\"*\n\x08Response\x12\x10\n\x08response\x18\x01 \x01(\x0c\x12\x0c\n\x04type\x18\x02 \x01(\t20\n\x05Model\x12\'\n\x04\x45xec\x12\x0e.proto.Request\x1a\x0f.proto.ResponseB\x04Z\x02./b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'model_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\002./'
  _globals['_REQUEST']._serialized_start=22
  _globals['_REQUEST']._serialized_end=62
  _globals['_RESPONSE']._serialized_start=64
  _globals['_RESPONSE']._serialized_end=106
  _globals['_MODEL']._serialized_start=108
  _globals['_MODEL']._serialized_end=156
# @@protoc_insertion_point(module_scope)
